"""initial_relational_schema"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "ac469dd784f2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("issuer", sa.String(length=500), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issuer", "subject"),
    )
    op.create_table(
        "accounts",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("opening_balance", sa.BigInteger(), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("type IN ('checking','savings','cash')", name="ck_accounts_0"),
        sa.CheckConstraint("version > 0", name="ck_accounts_version"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_accounts_owner_id"),
    )
    op.create_index(op.f("ix_accounts_owner_id"), "accounts", ["owner_id"], unique=False)
    op.create_table(
        "audit",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_owner_id"), "audit", ["owner_id"], unique=False)
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category_kind", sa.String(length=20), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("category_kind IN ('income','expense')", name="ck_categories_0"),
        sa.CheckConstraint("version > 0", name="ck_categories_version"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_categories_owner_id"),
    )
    op.create_index(op.f("ix_categories_owner_id"), "categories", ["owner_id"], unique=False)
    op.create_table(
        "demo_tokens",
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("digest"),
    )
    op.create_index(op.f("ix_demo_tokens_owner_id"), "demo_tokens", ["owner_id"], unique=False)
    op.create_table(
        "exercises",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("muscle_group", sa.String(length=100), nullable=False),
        sa.Column("equipment", sa.String(length=100), nullable=False),
        sa.Column("instructions", sa.String(), nullable=False),
        sa.Column("is_global", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version > 0", name="ck_exercises_version"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_exercises_owner_id"),
    )
    op.create_index(op.f("ix_exercises_owner_id"), "exercises", ["owner_id"], unique=False)
    op.create_table(
        "habits",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column("target_quantity", sa.Integer(), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("schedules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_date", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("target_quantity > 0", name="ck_habits_0"),
        sa.CheckConstraint("version > 0", name="ck_habits_version"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_habits_owner_id"),
    )
    op.create_index(op.f("ix_habits_owner_id"), "habits", ["owner_id"], unique=False)
    op.create_table(
        "idempotency",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("owner_id", "key"),
    )
    op.create_table(
        "integration_inbox",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("update_id", sa.String(length=100), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("update_id"),
    )
    op.create_table(
        "routines",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("exercises", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version > 0", name="ck_routines_version"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_routines_owner_id"),
    )
    op.create_index(op.f("ix_routines_owner_id"), "routines", ["owner_id"], unique=False)
    op.create_table(
        "task_lists",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version > 0", name="ck_task_lists_version"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_task_lists_owner_id"),
    )
    op.create_index(op.f("ix_task_lists_owner_id"), "task_lists", ["owner_id"], unique=False)
    op.create_table(
        "telegram_links",
        sa.Column("code_digest", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("chat_id", sa.String(length=80), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version > 0", name="ck_telegram_links_version"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_telegram_links_owner_id"),
    )
    op.create_index(op.f("ix_telegram_links_owner_id"), "telegram_links", ["owner_id"], unique=False)
    op.create_table(
        "cards",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("last_four", sa.String(length=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("close_day", sa.Integer(), nullable=False),
        sa.Column("due_day", sa.Integer(), nullable=False),
        sa.Column("limit_amount", sa.BigInteger(), nullable=True),
        sa.Column("payment_account_id", sa.Uuid(), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("close_day BETWEEN 1 AND 31", name="ck_cards_0"),
        sa.CheckConstraint("due_day BETWEEN 1 AND 31", name="ck_cards_1"),
        sa.CheckConstraint("limit_amount IS NULL OR limit_amount > 0", name="ck_cards_2"),
        sa.CheckConstraint("version > 0", name="ck_cards_version"),
        sa.ForeignKeyConstraint(
            ["owner_id", "payment_account_id"],
            ["accounts.owner_id", "accounts.id"],
            name="fk_cards_payment_account_id",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_cards_owner_id"),
    )
    op.create_index(op.f("ix_cards_owner_id"), "cards", ["owner_id"], unique=False)
    op.create_table(
        "habit_checkins",
        sa.Column("habit_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("quantity > 0", name="ck_habit_checkins_0"),
        sa.CheckConstraint("version > 0", name="ck_habit_checkins_version"),
        sa.ForeignKeyConstraint(
            ["owner_id", "habit_id"], ["habits.owner_id", "habits.id"], name="fk_habit_checkins_habit_id"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "habit_id", "date"),
        sa.UniqueConstraint("owner_id", "id", name="uq_habit_checkins_owner_id"),
    )
    op.create_index(op.f("ix_habit_checkins_owner_id"), "habit_checkins", ["owner_id"], unique=False)
    op.create_table(
        "integration_outbox",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("inbox_id", sa.Uuid(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["inbox_id"], ["integration_inbox.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("inbox_id"),
    )
    op.create_table(
        "recurrences",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("transaction_kind", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("day_of_month", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0", name="ck_recurrences_0"),
        sa.CheckConstraint("day_of_month BETWEEN 1 AND 31", name="ck_recurrences_1"),
        sa.CheckConstraint("version > 0", name="ck_recurrences_version"),
        sa.ForeignKeyConstraint(
            ["owner_id", "account_id"], ["accounts.owner_id", "accounts.id"], name="fk_recurrences_account_id"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "category_id"],
            ["categories.owner_id", "categories.id"],
            name="fk_recurrences_category_id",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_recurrences_owner_id"),
    )
    op.create_index(op.f("ix_recurrences_owner_id"), "recurrences", ["owner_id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("list_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("estimate_minutes", sa.Integer(), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checklist", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("priority IN ('none','low','medium','high')", name="ck_tasks_1"),
        sa.CheckConstraint("status IN ('todo','in_progress','done','cancelled')", name="ck_tasks_0"),
        sa.CheckConstraint("version > 0", name="ck_tasks_version"),
        sa.ForeignKeyConstraint(
            ["owner_id", "list_id"], ["task_lists.owner_id", "task_lists.id"], name="fk_tasks_list_id"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_tasks_owner_id"),
    )
    op.create_index(op.f("ix_tasks_owner_id"), "tasks", ["owner_id"], unique=False)
    op.create_table(
        "transfers",
        sa.Column("from_account_id", sa.Uuid(), nullable=False),
        sa.Column("to_account_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0", name="ck_transfers_0"),
        sa.CheckConstraint("from_account_id != to_account_id", name="ck_transfers_1"),
        sa.CheckConstraint("version > 0", name="ck_transfers_version"),
        sa.ForeignKeyConstraint(
            ["owner_id", "from_account_id"],
            ["accounts.owner_id", "accounts.id"],
            name="fk_transfers_from_account_id",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "to_account_id"],
            ["accounts.owner_id", "accounts.id"],
            name="fk_transfers_to_account_id",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_transfers_owner_id"),
    )
    op.create_index(op.f("ix_transfers_owner_id"), "transfers", ["owner_id"], unique=False)
    op.create_table(
        "workout_sessions",
        sa.Column("routine_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("volume", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("pr_count", sa.Integer(), nullable=False),
        sa.Column("exercises", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rest_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active','finished','cancelled')", name="ck_workout_sessions_0"),
        sa.CheckConstraint("version > 0", name="ck_workout_sessions_version"),
        sa.ForeignKeyConstraint(
            ["owner_id", "routine_id"],
            ["routines.owner_id", "routines.id"],
            name="fk_workout_sessions_routine_id",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_workout_sessions_owner_id"),
    )
    op.create_index(op.f("ix_workout_sessions_owner_id"), "workout_sessions", ["owner_id"], unique=False)
    op.create_index(
        "uq_active_session",
        "workout_sessions",
        ["owner_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "invoices",
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column("close_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("due_date > close_date", name="ck_invoices_0"),
        sa.CheckConstraint("version > 0", name="ck_invoices_version"),
        sa.ForeignKeyConstraint(
            ["owner_id", "card_id"], ["cards.owner_id", "cards.id"], name="fk_invoices_card_id"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "card_id", "close_date"),
        sa.UniqueConstraint("owner_id", "id", name="uq_invoices_owner_id"),
    )
    op.create_index(op.f("ix_invoices_owner_id"), "invoices", ["owner_id"], unique=False)
    op.create_table(
        "purchases",
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("installment_count", sa.Integer(), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active','cancelled','refunded')", name="ck_purchases_2"),
        sa.CheckConstraint("amount > 0", name="ck_purchases_0"),
        sa.CheckConstraint("installment_count > 0 AND installment_count <= amount", name="ck_purchases_1"),
        sa.CheckConstraint("version > 0", name="ck_purchases_version"),
        sa.ForeignKeyConstraint(
            ["owner_id", "card_id"], ["cards.owner_id", "cards.id"], name="fk_purchases_card_id"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "category_id"],
            ["categories.owner_id", "categories.id"],
            name="fk_purchases_category_id",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_purchases_owner_id"),
    )
    op.create_index(op.f("ix_purchases_owner_id"), "purchases", ["owner_id"], unique=False)
    op.create_table(
        "installments",
        sa.Column("purchase_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("close_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("is_refund", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount != 0", name="ck_installments_0"),
        sa.CheckConstraint("version > 0", name="ck_installments_version"),
        sa.ForeignKeyConstraint(
            ["owner_id", "invoice_id"],
            ["invoices.owner_id", "invoices.id"],
            name="fk_installments_invoice_id",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "purchase_id"],
            ["purchases.owner_id", "purchases.id"],
            name="fk_installments_purchase_id",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_installments_owner_id"),
    )
    op.create_index(op.f("ix_installments_owner_id"), "installments", ["owner_id"], unique=False)
    op.create_table(
        "invoice_payments",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0", name="ck_invoice_payments_0"),
        sa.CheckConstraint("version > 0", name="ck_invoice_payments_version"),
        sa.ForeignKeyConstraint(
            ["owner_id", "account_id"],
            ["accounts.owner_id", "accounts.id"],
            name="fk_invoice_payments_account_id",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "invoice_id"],
            ["invoices.owner_id", "invoices.id"],
            name="fk_invoice_payments_invoice_id",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_invoice_payments_owner_id"),
    )
    op.create_index(op.f("ix_invoice_payments_owner_id"), "invoice_payments", ["owner_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("transaction_kind", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("transfer_id", sa.Uuid(), nullable=True),
        sa.Column("invoice_id", sa.Uuid(), nullable=True),
        sa.Column("recurrence_id", sa.Uuid(), nullable=True),
        sa.Column("reversal_of", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('planned','posted','cancelled')", name="ck_transactions_1"),
        sa.CheckConstraint("transaction_kind IN ('income','expense')", name="ck_transactions_2"),
        sa.CheckConstraint("amount > 0", name="ck_transactions_0"),
        sa.CheckConstraint("version > 0", name="ck_transactions_version"),
        sa.ForeignKeyConstraint(
            ["owner_id", "account_id"],
            ["accounts.owner_id", "accounts.id"],
            name="fk_transactions_account_id",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "category_id"],
            ["categories.owner_id", "categories.id"],
            name="fk_transactions_category_id",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "invoice_id"],
            ["invoices.owner_id", "invoices.id"],
            name="fk_transactions_invoice_id",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "recurrence_id"],
            ["recurrences.owner_id", "recurrences.id"],
            name="fk_transactions_recurrence_id",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "reversal_of"],
            ["transactions.owner_id", "transactions.id"],
            name="fk_transactions_reversal_of",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "transfer_id"],
            ["transfers.owner_id", "transfers.id"],
            name="fk_transactions_transfer_id",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_transactions_owner_id"),
        sa.UniqueConstraint("owner_id", "recurrence_id", "date"),
    )
    op.create_index(op.f("ix_transactions_owner_id"), "transactions", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_owner_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_invoice_payments_owner_id"), table_name="invoice_payments")
    op.drop_table("invoice_payments")
    op.drop_index(op.f("ix_installments_owner_id"), table_name="installments")
    op.drop_table("installments")
    op.drop_index(op.f("ix_purchases_owner_id"), table_name="purchases")
    op.drop_table("purchases")
    op.drop_index(op.f("ix_invoices_owner_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(
        "uq_active_session", table_name="workout_sessions", postgresql_where=sa.text("status = 'active'")
    )
    op.drop_index(op.f("ix_workout_sessions_owner_id"), table_name="workout_sessions")
    op.drop_table("workout_sessions")
    op.drop_index(op.f("ix_transfers_owner_id"), table_name="transfers")
    op.drop_table("transfers")
    op.drop_index(op.f("ix_tasks_owner_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_recurrences_owner_id"), table_name="recurrences")
    op.drop_table("recurrences")
    op.drop_table("integration_outbox")
    op.drop_index(op.f("ix_habit_checkins_owner_id"), table_name="habit_checkins")
    op.drop_table("habit_checkins")
    op.drop_index(op.f("ix_cards_owner_id"), table_name="cards")
    op.drop_table("cards")
    op.drop_index(op.f("ix_telegram_links_owner_id"), table_name="telegram_links")
    op.drop_table("telegram_links")
    op.drop_index(op.f("ix_task_lists_owner_id"), table_name="task_lists")
    op.drop_table("task_lists")
    op.drop_index(op.f("ix_routines_owner_id"), table_name="routines")
    op.drop_table("routines")
    op.drop_table("integration_inbox")
    op.drop_table("idempotency")
    op.drop_index(op.f("ix_habits_owner_id"), table_name="habits")
    op.drop_table("habits")
    op.drop_index(op.f("ix_exercises_owner_id"), table_name="exercises")
    op.drop_table("exercises")
    op.drop_index(op.f("ix_demo_tokens_owner_id"), table_name="demo_tokens")
    op.drop_table("demo_tokens")
    op.drop_index(op.f("ix_categories_owner_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_audit_owner_id"), table_name="audit")
    op.drop_table("audit")
    op.drop_index(op.f("ix_accounts_owner_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_table("users")
    # ### end Alembic commands ###
